### ISSUE TITLE
Jest transform support / documentation 

### ISSUE THREAD

**Issue by aeirola** [ds300/react-native-typescript-transformer#21]
Hi, thanks for the awesome library. Nice to see proper TypeScript support in React Native.

As Jest is the default test runner in React Native projects created by by the `react-native` cli tool, it would be nice to see support or documentation on how to use this library as the transformer for Jest as well.

Of course the alternative is to use [`https://github.com/lozinsky/typescript-babel-jest`](https://github.com/lozinsky/https://github.com/lozinsky/typescript-babel-jest), but would somehow be nice to use the same transformation for tests and production.

**Comment by ds300** [comment]
Hey Axel :-)

I'd recommend using [ts-jest](https://github.com/kulshekhar/ts-jest). It is more mature than `lozinsky/typescript-babel-jest`.

It makes sense to use `react-native-typescript-transformer` with Jest to get the consistency between test and bundle code. Although I haven't run into any issues with `ts-jest` + the `react-native` Jest preset.

Here's my Jest config for reference:

```json
{
  "jest": {
    "preset": "react-native",
    "moduleDirectories": [
      "node_modules",
      "<rootDir>" // for absolute imports
    ],
    "transform": {
      "^.+\\.js$": "<rootDir>/node_modules/babel-jest",
      ".(ts|tsx)": "<rootDir>/node_modules/ts-jest/preprocessor.js"
    },
    "transformIgnorePatterns": [
      "node_modules/(?!(react-native|glamorous-native|react-native-global-props|react-native-elements|react-native-vector-icons|react-native-side-menu|react-native-tab-navigator|react-native-animatable|react-navigation)/)"
    ],
    "testRegex": "(/__tests__/.*|\\.(test|spec))\\.(ts|tsx|js)$",
    "moduleFileExtensions": [
      "ts",
      "tsx",
      "js",
      "json"
    ]
  },
}
```

I'd be open to figuring out how to do this, but ts-jest solves a lot of problems that I don't fancy solving again, so maybe it should be in collaboration with that project?

**Comment by GeeWee** [comment]
I help maintain ts-jest, and I'd love to keep these projects in sync somehow. (Love what you're doing here btw @ds300)

**Comment by ds300** [comment]
Hey @GeeWee That would would be awesome. Any ideas about how this could be done? It has been a long while since I looked at the ts-jest code.

**Comment by GeeWee** [comment]
I'm not actually sure what needs to be done,  ts-jest supports running things through Babel (with or without a babelrc) as a secondary transpilation step. (I think you added that originally) - does this transformer do any extra magic that'll cause the two projects to be incompatible?

**Comment by aminroosta** [comment]
With the following ...

```typescript
// __tests___/index.tsx
import {Text} from 'react-native';
import React from 'react';
import renderer from 'react-test-renderer';

it('renders correctly', () => {
  const tree = renderer.create( <Text /> ).toJSON();
  expect(tree).toMatchSnapshot();
});
```

```javascript
// package.json
    "jest": {
      "preset": "react-native",
      "moduleDirectories": [ "node_modules", "<rootDir>" ],
      "transform": {
        ".(ts|tsx)": "<rootDir>/node_modules/ts-jest/preprocessor.js"
      },
      "testRegex": "(/__tests__/.*|\\.(test|spec))\\.(ts|tsx|js)$",
      "moduleFileExtensions": [ "ts", "tsx", "js", "json" ]
    }
```

I get this :/

```
        3 | import renderer from 'react-test-renderer';
        4 | it('renders correctly', () => {
      > 5 |     const tree = renderer.create(<Text />).toJSON();
          |                                  ^
        6 |     expect(tree).toMatchSnapshot();
        7 | });
```

**Comment by GeeWee** [comment]
I would open a new issue in `ts-jest` :)

**Comment by vovkasm** [comment]
I just try preprocess jest tests with this module and it seems to work well with small glue code.
Although my test suite is small and I may not detect all edge cases, it would be good to have this "glue" in package itself and improve it together.

My config:
**jest/preprocessor.js** (actually it is adaptation of [RN jest preprocessor](https://github.com/facebook/react-native/blob/master/jest/preprocessor.js))
```js
const tsTransformer = require('react-native-typescript-transformer')
const rnTransformer = require('react-native/jest/preprocessor')

var preprocessor = Object.assign({}, rnTransformer, {
  process (src, file) {
    return tsTransformer.transform({
      filename: file,
      localPath: file,
      options: {
        dev: true,
        inlineRequires: true,
        platform: '',
        projectRoot: '',
        retainLines: true,
      },
      src,
    }).code
  },
})

module.exports = preprocessor
```

**package.json** (jest config part)
```json
  "jest": {
    "preset": "react-native",
    "transform": {
      "^.+\\.[jt]sx?$": "<rootDir>/jest/preprocessor.js"
    },
    "testMatch": [
      "**/*.spec.{js,jsx,ts,tsx}"
    ],
    "moduleFileExtensions": [
      "ts",
      "tsx",
      "js"
    ]
  },
```

What do you think?

**Comment by ds300** [comment]
@vovkasm This is cool! Thanks for sharing :)

I still haven't heard of anyone having problems with `ts-jest` (specifically caused by differences between it's transformer and react-native-typescript-transformer), and it solves a lot of edge cases, so I'm hesitant to put this in the package itself. But I'll gladly mention your solution in the README for other people who want to use exactly the same transformer in both places.

**Comment by vovkasm** [comment]
No problems with ts-jest, except hard to track deps. react-native-typescript-transformer requires math fewer other modules. :)

**Comment by momsse** [comment]
Hi @ds300 and @vovkasm,

First of all thanks for the works done with `ts-jest` and `react-native-typescript-transformer` that helps making `typescript` and `react-native` working together 👍 

Don't sure if it's the good place to explain my issue.

I'm using the transformer within an expo app and it do not work the same way when the code is run through the transformer and throught `ts-jest` during unit tests for `i18next` library. 

It fail to find `i18next.use` through `react-native-typescript-transformer` when i use the `import *` syntax but is ok with `import i18next from 'i18next'` (probably thanks to the babel magic).

Here a gist for the code and the output of `import * as i18next from 'i18next'` through `ts-jest` and `react-native-typescript-transformer` => https://gist.github.com/momsse/dfdd68f3f030d0236c69e971be26eda2

Tried the processor of @vovkasm without success:

```
__tests__/setupTests.ts: NodePath has been removed so is read-only. (This is an error on an internal node. Probably an internal error)
      
      at File.buildCodeFrameError (node_modules/babel-core/lib/transformation/file/index.js:427:15)
      at NodePath.buildCodeFrameError (node_modules/babel-traverse/lib/path/index.js:140:26)
      at NodePath._assertUnremoved (node_modules/babel-traverse/lib/path/removal.js:70:16)
      at NodePath.remove (node_modules/babel-traverse/lib/path/removal.js:20:8)
      at PluginPass.CallExpression (node_modules/babel-preset-fbjs/plugins/inline-requires.js:86:38)
      at newFn (node_modules/babel-traverse/lib/visitors.js:276:21)
      at NodePath._call (node_modules/babel-traverse/lib/path/context.js:76:18)
      at NodePath.call (node_modules/babel-traverse/lib/path/context.js:48:17)
      at NodePath.visit (node_modules/babel-traverse/lib/path/context.js:105:12)
      at TraversalContext.visitQueue (node_modules/babel-traverse/lib/context.js:150:16)
```

Any helps are welcome.

**Comment by maraujop** [comment]
Hi there,

Today i was suffering an issue in my tests, that I finally solved from using the previous gist and moving away of `ts-jest`. In my case it looked like in some reducers, some local variables weren't initialized where due and code would break in weird ways. I have tried for a while to isolate into a simpler test case without luck, I think some circular dependencies might be part of the problem.

Anyway, I just wanted to state that I've had problems and solved them with this.

Thanks

**Comment by GeeWee** [comment]
If you manage to produce a working repo I'd love to see it in ts-jest. 
Community-wise I still think it'd be optimal to focus the brunt on the resources inside ts-jest rather than having one solution for react and one for react native.
(Let me know if you think it's annoying that I chime in on this issue @ds300 , I'll gladly stop)

**Comment by ds300** [comment]
Happy to have your input @GeeWee !

I agree that it makes most sense to focus on ts-jest. It *should* work, and it has a lot of useful things that react-native-typescript-transformer lacks.

**Comment by aMarCruz** [comment]
@vovkasm your setup is not working for me. I have errors like this:
```bash
 FAIL  ~js/app/lib/__tests__/formatPhone.spec.js
  ● Test suite failed to run

    TypeError: Jest: a transform's `process` function must return a string, or an object with `code` key containing this string.
      
      at ScriptTransformer.transformSource (node_modules/jest-untime/build/script_transformer.js:238:15)
```

RN: 0.52.2
react-native-typescript-transformer: 1.2.3
Jest: 22.1.4
OS: Linux Mint 18.3

**Comment by vovkasm** [comment]
@aMarCrus: too new version of jest ))) it changed api for transformers, more info here: https://github.com/ds300/react-native-typescript-transformer/issues/39#issuecomment-356764981
